import sys
import nuke

r = nuke.createNode('Read')
r["file"].setValue(sys.argv[1])

w = nuke.createNode('Write')
w["file"].setValue(sys.argv[2])
w["file_type"].setValue("mov")
w["mov_prores_codec_profile"].setValue("ProRes 4:4:4:4 XQ 12-bit")
w["create_directories"].setValue(True)
w["colorspace"].setValue("color_picking")
w.setInput(0, r)

frames = nuke.rawArgs[-1].split(",")

r["last"].setValue(int(frames[-1]))
r["origlast"].setValue(int(frames[-1]))
r["origset"].setValue(True)

nuke.scriptSave(r"/users/animation/gjr215/Desktop/convertTest/output/autoGenerated.nk")

nuke.execute(w, int(frames[0]), int(frames[-1]))
